version: "3.10"

services:

  worker:

    build: .

    environment:

      - API_ID=${API_ID}

      - API_HASH=${API_HASH}

      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK=${WEBHOOK} 
      - DATABASE_URL=${DATABASE_URL} 
      - OWNER_ID=${OWNER_ID} 
